---
title: "Dashboard: Food Inspection"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: journal
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)


theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r data import, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
data(rest_inspec)

inspect = rest_inspec %>% 
  janitor::clean_names() %>% 
  filter(!boro %in% c("Missing"),
         grade %in%  c("P", "Z", "Not Yet Graded")) %>% 
  mutate(grade = recode(grade, "P" = "P: Pending on re-opening after an initial inspection resulting in a closure", "Z" = "Z: Pending")) %>% 
  select(boro, grade, score, critical_flag, inspection_date, cuisine_description)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Distribution of Scores among Spookiest (Pending) Grades

```{r}
inspect %>% 
  mutate(grade = fct_reorder(grade, score)) %>% 
  plot_ly(x = ~boro,
          y = ~score,
          color = ~grade,
          type = "box",
          colors = viridis(3, begin = 0.2, end = 0.8, option = "A")) %>% 
  layout(xaxis = list(title = "Borough"),
         yaxis = list(title = "Inspection Score"),
         boxmode = "group",
         legend = list(orientation = 'h'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Grades Among "Critical" Restaurants (hauntingly high!)

```{r}
rest_inspec %>% 
  filter(critical_flag == "Critical") %>%  
  count(grade) %>%
  mutate(grade = fct_reorder(grade, n)) %>% #to make bar chart in a particular order
  plot_ly(x = ~n,
          y = ~grade,
          color = ~grade,
          type = "bar",
          colors = viridis(6, begin = 0.1, end = 0.9, option = "A")) %>% 
  layout(xaxis = list(title = "Count"), yaxis = list(title = "Grade"))
```

### Chart C: Pending/Not Graded Inspection Scores among Pizza and Pizza/Italian Restaurants by Date

```{r}
inspect %>% 
  filter(cuisine_description %in% c("Pizza", "Pizza/Italian")) %>% 
  plot_ly(x = ~inspection_date,
          y = ~score,
          color = ~grade,
          type = "scatter",
          colors = viridis(3, begin = 0.3, end = 0.9, option = "A")) %>% 
  layout(xaxis = list(title = "Date of Inspection"),
         yaxis = list(title = "Inspection Score"),
         legend = list(x = 0, y = 1))
```

