---
title: "Priyanka Srinivasan"
output: html_document
---

<style type="text/css">
h1.title {text-align: center;}
</style>

<center>
# Resume
priyanka.srinivasan2013@gmail.com | [linkedin](https://www.linkedin.com/in/priyankasrinivasan/)
</center>

## Education

**Columbia University Mailman School of Public Health**, 2018 - 2020

*MPH in Biostatistics, Certificate in Health Policy and Practice*

  * **Relevant Coursework**: Health Systems, Global & Developmental Perspectives, Quantitative and Qualitative Research Methods Statistical Computing with SAS, Applied Regression I and II, Understanding the Healthcare Payer System, Health Economics, Data Science I

**Fordham University**, 2013 - 2017

*BS Psychology, minor in Business Administration, pre-medical track*

## Work Experience

**Columbia University**, August 2018 – May 2020

*Graduate Teaching Assistant*

  * Statistical Computing with SAS | Fall 2019, Spring 2020
  * Health Systems (Health Economics, US Public Health, Comparative Health Systems, Op-Ed writing workshop) | Fall 2019

**KPMG**,	June 2019 – August 2019

*Management Consulting Intern, Health and Government Solutions*

  * Provided project management support and produced weekly status reports to keep key stakeholders informed
  * Re-engineered a model for optimizing staffing based on needs of several stakeholders
  * Researched and presented a potential program and procurement to a high-level stakeholder based on which a whitepaper is being presented to persuade the Commissioner to pursue the program

**Translational Neuroimaging Laboratory, Albert Einstein School of Medicine**, (FT) July 2017 – July 2018, (PT) July 2018 – December 2018

*Clinical Research Coordinator* 

  * Responsible for QA of MRI images, executive dashboards, data analysis (SPSS), documentation, IRB-related communications, grant/budget proposals, and interviewing subjects for a study on TBI in soccer players

**Mood and Anxiety Disorders Program, Icahn School of Medicine at Mount Sinai**, March 2015 – November 2015, September 2016 – April 2017

*Clinical Research Intern*

  * Conducted 45-min phone screens research subjects, organized stored bio samples, and organized large study data (SPSS)

**St. John’s Riverside Hospital**, June 2015 – November 2015

*Medical Concierge/Scribe*

  * Composed chart documentation, billing, scribe program development for physicians in Emergency Department setting

## Leadership and Volunteer Experience

**Healthcare Data Analytics (Columbia)**,	January 2019 – Present

*VP of Finance*

  * Maintain records of financial transactions, budget allocation, contacting vendors, documentation, and organizing meetings/events

**Peer Health Exchange, Inc. (Fordham)**,	September 2013 – April 2017

*Co-Coordinator, Leadership Council Member, Health Educator*

  * Co-managed chapter of 60+ volunteers, tracked teaching of 130+ workshops scheduled at 6 Bronx high schools, led weekly teaching and cultural sensitivity trainings for health educators, taught HS students, adapted curriculum to student needs

**Care Package Delivery**, September 2014 – July 2015

*Project Coordinator*

  * Spearheaded a project to collect and donate care packages children/adolescents who suffer from mental illnesses at clinics in University of Virginia health system and an outpatient clinic in Chantilly, VA

## Presentations and Publications

  * **Srinivasan, P.** (2015, April). Cross-Cultural Attitudes on Women’s Rights at the UN. Oral presentation at the 43rd Annual Hunter College Psychology Conference, New York, NY.
  * TEDxFordham Talk: “Mental Health and Education”
  * **Srinivasan, P.** (2015). The 24th U.N. International Day of Older Persons. International Psychology Bulletin (Div. 52 of the APA),19(1), Winter 2015, 41-42.
  * Hunter LE, Freudenberg-Hua Y, Davies P, Mimi Kim, PhD; Richard B. Lipton, MD; Walter F. Stewart, PhD, MPH; **Priyanka Srinivasan, BS**; ShanShan Hu, MS; Michael L. Lipton, MD, PhD. Associations of Apolipoprotein E ε4 Genotype and Ball Heading With Verbal Memory in Amateur Soccer Players. JAMA Neurol. 2020;77(4):419–426. doi: 10.1001/jamaneurol.2019.4828
  * Eschliman, E.L., Garner, B.A., Le, T., **Srinivasan, P.**, & Fullilove, R.E. (June 2020). Police Transparency is a Public Health Issue, Too. Health Affairs Blog. doi: 10.1377/hblog20200625.221802


## Skills

  * SAS, REDCap, R, Python (currently learning), EMR (EPIC, Velos, Meditech), SPSS, Microsoft Office Suites (Word, Excel, PowerPoint, Access), Tableau (limited hands-on experience)
